### ISSUE TITLE
model embedding size 

### ISSUE THREAD

**Issue by atesnrllh** [laowangzi/Bert4XMR#1]
While the number of items is 8304, the number of item embedding vectors is 8309. Could you please explain why there is a discrepancy?
-- 0 is for padding. Encode since 1. 
self.last_item_index = 1
id_bank.item_index_id = 8304 
id_bank.last_item_index = 8305
config['item_num'] = id_bank.last_item_index+1
num_items = int(config['item_num']+1)
vocab_size = num_items + 2
-- len(vocab_size)= 8309

**Comment by laowangzi** [comment]
Hello,

Apologies for the delayed response, and thank you for your interest in our work. We have addressed your questions in our email. If you have any further questions, please let us know.
